### ISSUE TITLE
Looks useful, still using?

### ISSUE THREAD

**Issue by jessegrosjean** [Yoric/channels.rs#1]
Hi, thanks for releasing this, looks like just what I need.

I'm curious though if you still use (no update for 5 years) ... maybe you've found a better approach? For my particular use I'm sending events to the channel. Events are recursive enums... each different part of system sends a specific event type... don't want edge parts of system to have to know about or construct entire enum. Ie

```
SystemEvent
    ThingAEvent
        didThis
        didThat
        ... 
```

**Comment by Yoric** [comment]
The project for which I developed this has stopped a long time ago and I don't need this at the moment, so I'm afraid it's not really maintained.

I'll happily review patches, though!

**Comment by jessegrosjean** [comment]
So far seems to work fine, just wondering if you'd found some different approach that you liked better. Anyway, thanks!
